"""empty message

Revision ID: 78fa4ea1cd2d
Revises: 
Create Date: 2023-07-07 16:06:39.906319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78fa4ea1cd2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False, comment='设置主键自增'),
    sa.Column('type', sa.String(length=100), nullable=False, comment='service type, i.e. aiapp'),
    sa.Column('version', sa.String(length=100), nullable=False, comment='service version, i.e. 1.0.2'),
    sa.Column('host', sa.String(length=100), nullable=False, comment='host, i.e. 192.168.0.12'),
    sa.Column('port', mysql.INTEGER(display_width=11), nullable=False, comment='port, i.e. 8010'),
    sa.Column('path', sa.String(length=100), nullable=False, comment='path, i.e. /aipp'),
    sa.Column('ttl', mysql.INTEGER(display_width=11), nullable=False, comment='TTL, a countdown value, >0 active <=0 inactive'),
    sa.Column('active', mysql.TINYINT(display_width=1), nullable=False, comment='if actige, 1-active  0-inactive'),
    sa.Column('cpuload', sa.Float(), nullable=False, comment='cpu load, i.e. 25.03'),
    sa.Column('update_timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='timestamp of the last update'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False, comment='设置主键自增'),
    sa.Column('type', sa.String(length=100), nullable=False, comment='service type, i.e. aiapp'),
    sa.Column('stateless', mysql.TINYINT(display_width=1), nullable=False, comment='1-stateless  0-not stateless'),
    sa.Column('valid', mysql.TINYINT(display_width=1), nullable=False, comment='1-valid  0-invalid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False, comment='设置主键自增'),
    sa.Column('name', sa.String(length=500), nullable=False, comment='task name, i.e. nlt01.vtc365.com_4025_99395'),
    sa.Column('provider_id', mysql.INTEGER(display_width=11), nullable=False, comment='provider id in table provider'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='time of creating, i.e. 20230618 15:00:20'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='task status, i.e. CREATING, IP, STOPPED'),
    sa.Column('video_url', sa.String(length=500), nullable=False, comment='video url, i.e. http://test.vtc365.com/s22/1234/live.m3u8'),
    sa.Column('update_timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='timestamp of the last update'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('service')
    op.drop_table('provider')
    # ### end Alembic commands ###
