"""add version

Revision ID: ebc07d70a2b9
Revises: 4352e7fcee3b
Create Date: 2023-07-07 16:43:31.105501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc07d70a2b9'
down_revision = '4352e7fcee3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('version', sa.String(length=100), nullable=False, comment='service version, i.e. 1.0.2'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'version')
    # ### end Alembic commands ###
